### ISSUE TITLE
Exception occur when use library, if i solve this problem with androidx then error occur with databinding, but data binding already true in gradle. error still occur

### ISSUE THREAD

**Issue by rajam1215** [manojbhadane/Holdy#2]
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity;
        at com.manojbhadane.holdy.Holdy.Builder(Holdy.java:24)
        at com.royalways.pioneercranes.activity.MainActivity.onNavigationItemSelected(MainActivity.java:98)
        at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:170)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:352)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22646)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.royalways.pioneercranes-2/base.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.royalways.pioneercranes-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.royalways.pioneercranes-2/lib/arm, /system/lib, /vendor/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.manojbhadane.holdy.Holdy.Builder(Holdy.java:24) 
        at com.royalways.pioneercranes.activity.MainActivity.onNavigationItemSelected(MainActivity.java:98) 
        at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:170) 
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840) 
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158) 
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991) 
        at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:352) 
        at android.view.View.performClick(View.java:5675) 
        at android.view.View$PerformClick.run(View.java:22646) 
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6251) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by rajam1215** [comment]
and please change in documentation according androidx and databiding

**Comment by manojbhadane** [comment]
Ok.. did u solve your issues with  androidx and databinding

**Comment by rajam1215** [comment]
@manojbhadane 
2019-05-03 09:59:29.628 8172-8172/com.royalways.pioneercranes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.royalways.pioneercranes, PID: 8172
    java.lang.NoSuchMethodError: No direct method <init>(Landroidx/databinding/DataBindingComponent;Landroid/view/View;I)V in class Landroidx/databinding/ViewDataBinding; or its super classes (declaration of 'androidx.databinding.ViewDataBinding' appears in /data/app/com.royalways.pioneercranes-2/split_lib_dependencies_apk.apk)
        at com.manojbhadane.holdy.databinding.ActivityHolderBinding.<init>(ActivityHolderBinding.java:23)
        at com.manojbhadane.holdy.databinding.ActivityHolderBindingImpl.<init>(ActivityHolderBindingImpl.java:32)
        at com.manojbhadane.holdy.databinding.ActivityHolderBindingImpl.<init>(ActivityHolderBindingImpl.java:29)
        at com.manojbhadane.holdy.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:40)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:327)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:306)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.manojbhadane.holdy.HolderActivity.onCreate(HolderActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:6666)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

This error come after update appcompact to androidx and update to databinding

you do this type of coding for databinding in mainActivity
ActivityMainBinding dataBinding = DataBindingUtil.setContentView(this, R.layout.activity_main);

but i don't do this type of coding
please solve that issue, or give some alternate

**Comment by rajam1215** [comment]
@manojbhadane
i don't think so it is necessary to do in code means data binding code. i already enable in gradle.

but give this type of error. 

if some one not full familiar with androidx and databinding, then this library is not useful or useless, coz they don't do anything with this.

**Comment by manojbhadane** [comment]
Document is updated.. please check
