### ISSUE TITLE
after migrate to androidx and enable databinding in gradle still error occur

### ISSUE THREAD

**Issue by rajam1215** [manojbhadane/Holdy#4]
2019-05-03 09:59:29.628 8172-8172/com.royalways.pioneercranes E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.royalways.pioneercranes, PID: 8172
java.lang.NoSuchMethodError: No direct method (Landroidx/databinding/DataBindingComponent;Landroid/view/View;I)V in class Landroidx/databinding/ViewDataBinding; or its super classes (declaration of 'androidx.databinding.ViewDataBinding' appears in /data/app/com.royalways.pioneercranes-2/split_lib_dependencies_apk.apk)
at com.manojbhadane.holdy.databinding.ActivityHolderBinding.(ActivityHolderBinding.java:23)
at com.manojbhadane.holdy.databinding.ActivityHolderBindingImpl.(ActivityHolderBindingImpl.java:32)
at com.manojbhadane.holdy.databinding.ActivityHolderBindingImpl.(ActivityHolderBindingImpl.java:29)
at com.manojbhadane.holdy.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:40)
at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
at androidx.databinding.DataBindingUtil.bindToAddedViews(DataBindingUtil.java:327)
at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:306)
at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
at com.manojbhadane.holdy.HolderActivity.onCreate(HolderActivity.java:40)
at android.app.Activity.performCreate(Activity.java:6666)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6251)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

This error come after update appcompact to androidx and update to databinding

you do this type of coding for databinding in mainActivity
ActivityMainBinding dataBinding = DataBindingUtil.setContentView(this, R.layout.activity_main);

but i don't do this type of coding
please solve that issue, or give some alternate

**Comment by manojbhadane** [comment]
Added some fix.. check if its works for you or not
Please update dependancy

`	 implementation 'com.github.manojbhadane:Holdy:v1.6.1`

**Comment by rajam1215** [comment]
@manojbhadane 
thanks for reply, i check in 5 minutes and revert you. please feel free to read my overview.

**Comment by rajam1215** [comment]
@manojbhadane 
It is working, thanks for solution.

but i want to ask it is necessary, convert project in appComapct to androidx or enable data binding in gradle.

or library work without this type of stuff in newer version.

**Comment by manojbhadane** [comment]
Not required i think.

**Comment by rajam1215** [comment]
@manojbhadane 

No without databinding and androidx conversion, app not working, give error, please update in read.md file or documentation.

Thanks

**Comment by rajam1215** [comment]
@manojbhadane 

add please enhance this library androidx to appcompact, because some of feature not work in androidx, and proper documentation in git. 

Thanks

**Comment by rajam1215** [comment]
@manojbhadane 

This error come please solve that issue. it is necessary. 

ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-23:19 to override.
